### ISSUE TITLE
Target customer profile

### ISSUE THREAD

**Issue by akalitenya** [so-epic/kickoff#4]
What is the size of the target customer? How many users?

**Comment by tgig** [comment]
We are targeting companies from 20-50 people to start, with ~20% of the people having seats to use the tool. (I.e., in a 50 person company they would have 10 seats).

The intention is to go up-market over time as we learn more about their needs. That's where the money is at, but also much harder to enter, so we will start with smaller companies.

**Comment by akalitenya** [comment]
Excellent. I think that Git based workflow will be especially useful for companies that have at least 2 people as a Data Engineer / Data Analyst role.
